# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        # test against latest update of each major Java version, as well as specific updates of LTS versions:
        java: [ 11.0.x ]

    steps:
    
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    
    - name: Build with Maven
      run: mvn -B package --file astreu4j/pom.xml
    
    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy --file astreu4j/pom.xml -s $GITHUB_WORKSPACE/astreu4j/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
